### ISSUE TITLE
Add red asterisks to required form fields

### ISSUE THREAD

**Issue by postmodern** [ronin-rb/ronin-app#31]
Add the typical red asterisk to all required form fields.

Could add this as a [CSS class](https://github.com/jgthms/bulma/issues/2529#issuecomment-857607990).

```css
.label.is-required::after {
  content: ' *';
  color: red;
}
```

Would also need to add the usual blurb text "<red asterisk> means a required field" to the forms.
